Fix missing "re" import
> Downloading: Coldplay feat. Little Simz, Burna Boy, Elyanna & TINI - WE PRAY (single version)
> Traceback (most recent call last):
>   File "/home/cweiske/Dev/lyrico/./lyrico-runner.py", line 12, in <module>
>     main()
>     ~~~~^^
>   File "/home/cweiske/Dev/lyrico/lyrico/lyrico.py", line 100, in main
>     song.download_lyrics()
>     ~~~~~~~~~~~~~~~~~~~~^^
>   File "/home/cweiske/Dev/lyrico/lyrico/song.py", line 112, in download_lyrics
>     variants += [[self.artist, re.sub(r'\([^)]+ersion\)$', '', self.title)]]
>                                ^^
> NameError: name 're' is not defined. Did you forget to import 're'?